-- Rich room descriptions (UTF-8) — EN base + VI translations
USE shinning_hotel;
SET NAMES utf8mb4;

UPDATE rooms SET description = '<p class="room-lead">A refined <strong>25&nbsp;m²</strong> urban retreat with a king-size bed, sweeping city views, and a rejuvenating rain shower — crafted for guests who value calm, comfort, and a central address.</p><h3>Room highlights</h3><ul class="room-feature-list"><li>Floor-to-ceiling windows with skyline views</li><li>Premium king mattress with signature linens</li><li>Spa-inspired rain shower &amp; luxury toiletries</li><li>High-speed WiFi &amp; smart TV entertainment</li></ul><h3>Perfect for</h3><p>Couples, solo travellers, and short business stays who want boutique service without compromise.</p>' WHERE slug = 'standard-king';

UPDATE rooms SET description = '<p class="room-lead">Wake to the horizon in this <strong>40&nbsp;m²</strong> sanctuary — floor-to-ceiling glass, a separate lounge nook, and refined finishes create an effortless escape above the city.</p><h3>Room highlights</h3><ul class="room-feature-list"><li>Panoramic ocean &amp; city vistas</li><li>Deep-soaking bathtub &amp; walk-in shower</li><li>Lounge seating for in-room dining</li><li>24-hour in-room dining available</li></ul><h3>Perfect for</h3><p>Romantic getaways, anniversaries, and guests who appreciate space and a cinematic view.</p>' WHERE slug = 'deluxe-ocean-view';

UPDATE rooms SET description = '<p class="room-lead">Our crown jewel: <strong>120&nbsp;m²</strong> of private luxury with a terrace, dedicated butler, and dining salon — where every detail whispers exclusivity.</p><h3>Room highlights</h3><ul class="room-feature-list"><li>Private terrace with outdoor seating</li><li>Butler service &amp; personalized turndown</li><li>Jacuzzi, separate living &amp; dining areas</li><li>Complimentary minibar selection</li></ul><h3>Perfect for</h3><p>Discerning travellers, celebrations, and extended stays demanding privacy and prestige.</p>' WHERE slug = 'presidential-suite';

UPDATE rooms SET description = '<p class="room-lead">Smart, flexible <strong>28&nbsp;m²</strong> comfort with two premium single beds — ideal for friends or colleagues sharing a sophisticated city base.</p><h3>Room highlights</h3><ul class="room-feature-list"><li>Twin beds with luxury bedding</li><li>Work desk &amp; ergonomic seating</li><li>In-room safe &amp; minibar</li><li>City views &amp; rain shower</li></ul><h3>Perfect for</h3><p>Friends travelling together, colleagues, and guests who prefer twin bedding.</p>' WHERE slug = 'standard-twin';

UPDATE rooms SET description = '<p class="room-lead">Serenity meets style in <strong>38&nbsp;m²</strong> overlooking our courtyard garden — a soaking tub, private balcony, and soft natural light invite you to unwind.</p><h3>Room highlights</h3><ul class="room-feature-list"><li>Private balcony facing the garden</li><li>Deep soaking tub &amp; premium bath amenities</li><li>Nespresso &amp; curated minibar</li><li>Spacious wardrobe &amp; vanity area</li></ul><h3>Perfect for</h3><p>Guests seeking a quieter atmosphere with greenery and spa-like bathing rituals.</p>' WHERE slug = 'deluxe-garden-view';

UPDATE rooms SET description = '<p class="room-lead"><strong>65&nbsp;m²</strong> of connected space with a lounge — thoughtfully designed so families and small groups stay together in comfort and style.</p><h3>Room highlights</h3><ul class="room-feature-list"><li>Connecting rooms with shared lounge</li><li>Sleeps up to five guests comfortably</li><li>Dual bathrooms &amp; generous storage</li><li>Child-friendly amenities on request</li></ul><h3>Perfect for</h3><p>Families, multi-generational trips, and groups who value space and togetherness.</p>' WHERE slug = 'family-connecting';

UPDATE rooms SET description = '<p class="room-lead">Elevate your stay in <strong>42&nbsp;m²</strong> with exclusive club lounge access, a dedicated workspace, and express check-in — built for the modern business traveller.</p><h3>Room highlights</h3><ul class="room-feature-list"><li>Club lounge breakfast &amp; evening cocktails</li><li>Executive desk &amp; high-speed connectivity</li><li>Express check-in / late checkout (subject to availability)</li><li>Premium coffee station in-room</li></ul><h3>Perfect for</h3><p>Executives, frequent flyers, and guests who value productivity and privileged access.</p>' WHERE slug = 'executive-club-king';

UPDATE rooms SET description = '<p class="room-lead">The skyline is yours from <strong>150&nbsp;m²</strong> at the top of Shinning — an iconic penthouse with jacuzzi, butler service, and entertaining space for unforgettable moments.</p><h3>Room highlights</h3><ul class="room-feature-list"><li>360° panoramic city &amp; ocean views</li><li>Private jacuzzi &amp; expansive terrace</li><li>Formal dining for intimate gatherings</li><li>Dedicated butler &amp; VIP arrival service</li></ul><h3>Perfect for</h3><p>Honeymoons, milestone celebrations, and guests who expect nothing less than extraordinary.</p>' WHERE slug = 'penthouse-sky';

UPDATE room_translations rt JOIN rooms r ON r.id = rt.room_id SET rt.description = '<p class="room-lead">Không gian <strong>25&nbsp;m²</strong> tinh tế với giường king, view thành phố và vòi sen mưa — dành cho khách yêu sự tĩnh lặng và tiện nghi cao cấp giữa lòng đô thị.</p><h3>Điểm nổi bật</h3><ul class="room-feature-list"><li>Cửa sổ lớn ngắm skyline</li><li>Nệm king &amp; ga trải cao cấp</li><li>Vòi sen mưa &amp; amenities sang trọng</li><li>WiFi tốc độ cao &amp; smart TV</li></ul><h3>Phù hợp cho</h3><p>Cặp đôi, khách công tác và kỳ nghỉ ngắn ngày.</p>' WHERE rt.locale = 'vi' AND r.slug = 'standard-king';

UPDATE room_translations rt JOIN rooms r ON r.id = rt.room_id SET rt.description = '<p class="room-lead"><strong>40&nbsp;m²</strong> hướng biển với cửa kính trần-sàn, góc lounge riêng — bắt đầu mỗi ngày trong ánh sáng và không gian rộng rãi.</p><h3>Điểm nổi bật</h3><ul class="room-feature-list"><li>View biển &amp; thành phố panorama</li><li>Bồn tắm sâu &amp; phòng tắm walk-in</li><li>Khu vực tiếp khách trong phòng</li><li>Phục vụ phòng 24/7</li></ul><h3>Phù hợp cho</h3><p>Kỳ nghỉ lãng mạn, kỷ niệm và khách thích không gian rộng.</p>' WHERE rt.locale = 'vi' AND r.slug = 'deluxe-ocean-view';

UPDATE room_translations rt JOIN rooms r ON r.id = rt.room_id SET rt.description = '<p class="room-lead"><strong>120&nbsp;m²</strong> đẳng cấp với sân thượng riêng, quản gia và phòng ăn — trải nghiệm dành riêng cho khách khó tính nhất.</p><h3>Điểm nổi bật</h3><ul class="room-feature-list"><li>Sân thượng &amp; khu vực ngoài trời riêng</li><li>Dịch vụ quản gia cá nhân</li><li>Jacuzzi, phòng khách &amp; phòng ăn tách biệt</li><li>Minibar cao cấp miễn phí</li></ul><h3>Phù hợp cho</h3><p>Kỳ nghỉ dài ngày, sự kiện đặc biệt và khách VIP.</p>' WHERE rt.locale = 'vi' AND r.slug = 'presidential-suite';

UPDATE room_translations rt JOIN rooms r ON r.id = rt.room_id SET rt.description = '<p class="room-lead"><strong>28&nbsp;m²</strong> với hai giường đơn cao cấp — lựa chọn lý tưởng cho bạn bè hoặc đồng nghiệp đi cùng.</p><h3>Điểm nổi bật</h3><ul class="room-feature-list"><li>Hai giường đơn tiện nghi</li><li>Bàn làm việc &amp; ghế ergonomic</li><li>Két an toàn &amp; minibar</li><li>View thành phố &amp; vòi sen mưa</li></ul><h3>Phù hợp cho</h3><p>Nhóm bạn, khách công tác cùng phòng.</p>' WHERE rt.locale = 'vi' AND r.slug = 'standard-twin';

UPDATE room_translations rt JOIN rooms r ON r.id = rt.room_id SET rt.description = '<p class="room-lead"><strong>38&nbsp;m²</strong> nhìn ra vườn nội khu — bồn ngâm, ban công riêng và ánh sáng dịu mang đến cảm giác thư thái.</p><h3>Điểm nổi bật</h3><ul class="room-feature-list"><li>Ban công hướng vườn</li><li>Bồn ngâm &amp; amenities spa</li><li>Máy pha cà phê &amp; minibar</li><li>Tủ quần áo &amp; khu trang điểm rộng</li></ul><h3>Phù hợp cho</h3><p>Khách thích không gian xanh và yên tĩnh.</p>' WHERE rt.locale = 'vi' AND r.slug = 'deluxe-garden-view';

UPDATE room_translations rt JOIN rooms r ON r.id = rt.room_id SET rt.description = '<p class="room-lead"><strong>65&nbsp;m²</strong> phòng liền kề với lounge — gia đình và nhóm nhỏ ở cùng nhau thoải mái, sang trọng.</p><h3>Điểm nổi bật</h3><ul class="room-feature-list"><li>Phòng connecting &amp; lounge chung</li><li>Ở tối đa 5 khách</li><li>Hai phòng tắm &amp; không gian lưu trữ lớn</li><li>Tiện ích trẻ em theo yêu cầu</li></ul><h3>Phù hợp cho</h3><p>Gia đình và nhóm du lịch.</p>' WHERE rt.locale = 'vi' AND r.slug = 'family-connecting';

UPDATE room_translations rt JOIN rooms r ON r.id = rt.room_id SET rt.description = '<p class="room-lead"><strong>42&nbsp;m²</strong> kèm quyền lợi Club Lounge, bàn làm việc và nhận phòng nhanh — thiết kế cho khách công tác hiện đại.</p><h3>Điểm nổi bật</h3><ul class="room-feature-list"><li>Club Lounge: bữa sáng &amp; cocktail tối</li><li>Bàn executive &amp; WiFi tốc độ cao</li><li>Check-in/out ưu tiên (tùy tình trạng)</li><li>Trạm pha cà phê cao cấp</li></ul><h3>Phù hợp cho</h3><p>Doanh nhân và khách bay thường xuyên.</p>' WHERE rt.locale = 'vi' AND r.slug = 'executive-club-king';

UPDATE room_translations rt JOIN rooms r ON r.id = rt.room_id SET rt.description = '<p class="room-lead"><strong>150&nbsp;m²</strong> tầng thượng — jacuzzi riêng, quản gia và không gian tiệc tùng trước panorama thành phố.</p><h3>Điểm nổi bật</h3><ul class="room-feature-list"><li>View panorama 360°</li><li>Jacuzzi &amp; sân thượng rộng</li><li>Phòng ăn cho tiệc riêng</li><li>Quản gia &amp; đón VIP</li></ul><h3>Phù hợp cho</h3><p>Trăng mật, kỷ niệm và kỳ nghỉ đặc biệt nhất.</p>' WHERE rt.locale = 'vi' AND r.slug = 'penthouse-sky';
